# Author: Simon Blanke
# Email: simon.blanke@yahoo.com
# License: MIT License
os:
  - linux

language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install packaging
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install -r requirements.txt

script:
  - pytest --cov=gradient_free_optimizers/ -p no:warnings

after_success:
  - coveralls
