# Author: Simon Blanke
# Email: simon.blanke@yahoo.com
# License: MIT License
os:
  - linux

language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install scipy
  - pip install numpy>=1.18.1
  - pip install pandas
  - pip install scikit-learn>=0.22.1
  - pip install tqdm
  - pip install packaging
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install .

script:
  - pytest --cov=gradient_free_optimizers/ -p no:warnings

after_success:
  - coveralls
